### ISSUE TITLE
deeply nested setting

### ISSUE THREAD

**Issue by willkg** [mahmoud/glom#13]
I work on a project that flings around deeply nested Python structures with wild abandon. glom nicely handles the "get something from this structure even if all the branches of the path aren't there" and now I can replace some code I wrote. Yay!

The other side of things that I need to handle is setting a value in a deeply nested structure where the branches of the path may not be there.

For example, maybe something like this which uses dicts:

```
>>> from glom import glom_set
>>> foo = {}
>>> glom_set(foo, 'a.b.c', value=5)
>>> foo
{'a': {'b': {'c': 5}}}
```

There are more complex tree manipulations that could be done, but at the moment I'm thinking about setting a single leaf value.

Is manipulating deeply nested data structures in place in-scope for glom?

**Comment by mahmoud** [comment]
Hey Will! It's a pretty tricky problem, especially since glom specs are full Python. Still, I think @kurtbrose and I came up with an approach that could enable this. This thread might take a very glom-internals-heavy turn as we scope this out :)

Kurt, I'm making a note for us here: Currently the path is tracked "only" for error reporting, but if we're going to do setting, we need to get fancier. In particular, tuple chains produce intermediate targets who are on the path for debugging reasons, but wouldn't be valid for a Replace type specifier. Something to chat about at PyCon?

**Comment by willkg** [comment]
Thank you for thinking about it!

I'm not at PyCon this year, but I'm happy to help where I can. Just let me know!

**Comment by kurtbrose** [comment]
we're working on `Assign` spec and `assign` helper https://github.com/mahmoud/glom/pull/44

**Comment by mahmoud** [comment]
Good news, @willkg! With the glom 18.3.0 release, we now have an assign() function, as well as an `Assign` spec type (for performing multiple assignments in the same glom call, among other things). Docs here:

https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign

Give it a whirl, and let us know how you like it! Thanks again for the request!

**Comment by willkg** [comment]
I'll try to tinker with it tomorrow and let you know. Thank you for doing this!

**Comment by willkg** [comment]
Sorry it took so long to look at this. It's helpful, but it doesn't cover the deeply-nested need in the example I gave:

```
$ python
Python 2.7.14 (default, Dec 12 2017, 06:55:29) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import glom
>>> foo = {}
>>> glom.assign(foo, 'a.b.c', 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/glom/mutable.py", line 152, in assign
    return glom(obj, Assign(path, val))
  File "/usr/local/lib/python2.7/site-packages/glom/core.py", line 1391, in glom
    ret = _glom(target, spec, scope)
  File "/usr/local/lib/python2.7/site-packages/glom/core.py", line 1406, in _glom
    return spec.glomit(target, scope)
  File "/usr/local/lib/python2.7/site-packages/glom/mutable.py", line 120, in glomit
    dest = scope[glom](target, self.path, scope)
  File "/usr/local/lib/python2.7/site-packages/glom/core.py", line 1406, in _glom
    return spec.glomit(target, scope)
  File "/usr/local/lib/python2.7/site-packages/glom/core.py", line 282, in glomit
    return _t_eval(target, self.path_t, scope)
  File "/usr/local/lib/python2.7/site-packages/glom/core.py", line 873, in _t_eval
    raise PathAccessError(e, Path(_t), i // 2)
glom.core.PathAccessError: could not access 'a', part 0 of Path('a', 'b'), got error: KeyError('a',)
>>> 
```

I read through the issue comments and the PR comments and don't see anything obvious that suggested that you decided not to tackle what to do when parts of the path are missing.

Do you want me to write up another issue for that or is it not doable? Alternatively, would you suggest I write my own specifier?

**Comment by kurtbrose** [comment]
yes true, this doesn't solve the problem

you could combine it with something like the self-referencing default-dict trick

```
import glom
import collections
treedict = lambda: collections.defaultdict(treedict)
foo = treedict()
glom.assign(foo, 'a.b.c', 5)
# defaultdict(<function <lambda> at 0x0000000003721D68>, {'a': defaultdict(<function <lambda> at 0x0000000003721D68>, {'b': defaultdict(<function <lambda> at 0x0000000003721D68>, {'c': 5})})})
```

**Comment by kurtbrose** [comment]
(maybe we could address this by having a "missing" or "default" argument to assign that says, "if missing intermediate value, put one of these there" -- akin to __missing__ on dict or defaultdict)

**Comment by kurtbrose** [comment]
```assign(foo, 'a.b.c', 5, missing=dict)``` ?

**Comment by willkg** [comment]
Also, I don't intend to come across as ungrateful. I really appreciate the work you're putting into this. Thank you!

**Comment by mahmoud** [comment]
I'm on honeymoon ATM, but Kurt pretty much covered my ideas completely. I
think a default arg for assign makes sense, though might need a more
specific name than just default.

The defaultdict/treedict approach might work for some cases but if
replacing the container works, then you probably wouldn't need assign :)

Looking forward to making a new release once I'm back!

**Comment by kurtbrose** [comment]
will -- really glad that you find glom is useful -- it's hard to predict the corner cases / pain points until you try to do things with the library so your feedback is invaluable to improving the library for everyone; please keep reporting where you get stuck! and don't worry about offending us :-)

I've reopened the issue, we'll take it on as "add good customization of set-values-to-this-if-missing to assign"

**Comment by jeshan** [comment]
Kurt, I used your default dict tree as a workaround and it looks like it can work for dicts and not for lists yet.
For example, I have:
```python
treedict = lambda: collections.defaultdict(treedict)
target = treedict()
glom.assign(target, 'a.b.0.c', 5)
```

I was expecting `target == {'a': {'b': [{'c': 5}]}}` to return True
but instead it was `target == {'a': {'b': {'0': {'c': 5}}}}` that returned True

Should I use the lambda differently or is this currently a glom limitation?

**Comment by kurtbrose** [comment]
this is due to an inherent ambiguity between `{0: val}` and `[val]`

lets see.... first off: `T['a']['b'][0]['c']` will make the path to be set more explicit (so you don't get integer vs string ambiguity)

that still leaves you with ` {'a': {'b': {0: {'c': 5}}}}`

I don't think the approach of `defaultdict` (or `__missing__`) will get past that; when `__getitem__` is called with 'b', it has to decide what object to return -- it doesn't know if that object is going to be accessed as `[0]` or `[astring]`.  The left-to-right operator evaluation makes it impossible for the object to "see the future" and know what kind of value to implicitly create.

hmmm... as mentioned earlier, a missing callback argument of assign might be a way to handle this -- that callback could be handed the whole path and "peek ahead" to see how an object is used

that still feels kind of arbitrary and ad-hoc

**Comment by mahmoud** [comment]
Yeah, I'm down to make a `missing` callback, but I was thinking this would mostly be for convenience and clarity. As in, a callable, called with no arguments, like `dict` or `list`. Not both. 

If we're talking context-sensitive object creation then I don't think the resulting API will be very convenient or clear. And that's without getting into the problems with non-contiguous list assignments. (i.e., try 1 instead of 0)
