### ISSUE TITLE
Would need to downgrade `glom` to upgrade its transitive dep `face`

### ISSUE THREAD

**Issue by mosbasik** [mahmoud/glom#284]
My team has pinned the newest current version `glom==23.5.0` and its transitive dep `face==20.1.1` (the version just before current newest version `face==22.0.0`).

`glom` has required `face<22.0.0` since `glom==23.1.0` (https://github.com/mahmoud/glom/commit/d4f40282e80acf42cfbf038218e51afb4c2a3f3a#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L4)

This means we *could* upgrade to `face==22.0.0` but only if we also downgraded to `glom<23.1.0`, which sounds like *not the intended progression* of upgrades and probably a terrible idea. :wink: 

Decided it was worth opening an issue to see if this is an oversight or if there's a plan about this already.

I assume for now my team should just tell dependabot to stop trying to upgrade `face` until `glom` releases a version that can use the latest `face`?

**Comment by mahmoud** [comment]
Oof, yeah. I think the stricter version was put in there because something wasn't playing nice. We should really resolve that and get the newest versions all tested and playing nicely together. Thanks for the heads up!

**Comment by mahmoud** [comment]
OK v24.11.0 just landed on PyPI, with an unpinned face dep: https://pypi.org/manage/project/glom/releases/

Nearest I can tell, this was because I dropped py2 support in face before glom, and I hurriedly added that pin without making a note to remove it once glom dropped py2 support as well. Hopefully all's well that ends well, :crossed_fingers: no py3->py4 issues anytime soon :)
