### ISSUE TITLE
Is there a way to add an element to a list?

### ISSUE THREAD

**Issue by argenisleon** [mahmoud/glom#99]
Hi,
I just want to and element to a list like this. 
```
a = {"list":[1,2,3]}
b = glom(a, "list")
b.append(4)
assign(a,"list", b)

Output:
{'list': [1, 2, 3, 4]}
```

Is there a shortcut in glom?

**Comment by mahmoud** [comment]
There is! You can use [the `T` object](https://glom.readthedocs.io/en/latest/api.html#object-oriented-access-and-method-calls-with-t) to access all the methods and wonders of the target object:

```python
>>> from glom import glom, T
>>> glom(a, ('list', T.append(4)))
>>> a
{'list': [1, 2, 3, 4]}
```

I used a tuple to chain access to the list, then use the `list` type's `.append()` method like usual. Note that if the `"list"` key is missing from `a`, and you don't want a `PathAccessError`, you'll want to use [Coalesce](https://glom.readthedocs.io/en/latest/api.html#conditional-access-and-defaults-with-coalesce) to create a default list. :)

Not strictly related here, but because Python assignments are statements, not expressions, you can use [the `Assign` specifier type](https://glom.readthedocs.io/en/latest/api.html#target-mutation-with-assign) for other types of assignment (such as to specific list index).

Hope that helps! Also, feel free to ask [on StackOverflow for better referenceability](https://stackoverflow.com/tags/glom/)  :)
